// import { getSongByTrackName } from "./Fetches/deezer";
// import axios from "axios";

const REGGAE_SONGS = [
  { artist: "Shaggy", song: "Boombastic" },
  { artist: "Shaggy", song: "Angel" },
  { artist: "Shaggy", song: " It Wasn't Me" },
  { artist: "Sean paul", song: "mad love" },
  { artist: "Bob Marley", song: "Could You Be Loved" },
  { artist: "Bob Marley", song: "Is This Love" },
  { artist: "Bob Marley", song: "Jamming" },
  { artist: "Bob Marley", song: "One Love" },
  { artist: "Bob Marley", song: "Stir It Up" },
  { artist: "Bob Marley", song: "Redemption Song" },
  { artist: "Bob Marley", song: "one love" },
  { artist: "Bob Marley", song: "No Woman, No Cry" },
  { artist: "Bob Marley", song: "waiting in vain" },
  { artist: "Bob Marley", song: "get up stand up" },
  { artist: "Damian Marley", song: "patience" },
  { artist: "Damian Marley", song: "Welcome to Jamrock" },
  { artist: "Ziggy Marley", song: "Beach In Hawaii" },
  { artist: "Ziggy Marley", song: "love is my religion" },
  { artist: "Valiant", song: "Dunce Cheque" },
  { artist: "Valiant", song: "Speed Off" },
  { artist: "Koffee", song: "Pull Up" },
  { artist: "Koffee", song: "Toast" },
  { artist: "Stick Figure", song: "Sound of the Sea" },
  { artist: "Stick Figure", song: "Edge of the Ocean" },
  { artist: "Stick Figure", song: "Choice Is Yours" },
  { artist: "Stick Figure", song: "Smokin' Love " },
  { artist: "Stick Figure", song: "Once in a Lifetime" },
  { artist: "Stick Figure", song: "Angels Above Me" },
  { artist: "Stick Figure", song: "In This Love" },
  { artist: "Stick Figure", song: "world on fire" },
  { artist: "Popcaan", song: "Next To Me " },
  { artist: "Sean Paul", song: "No Lie" },
  { artist: "Spice", song: "Go Down Deh " },
  { artist: "Wayne Wonder", song: "No Letting Go" },
  { artist: "Justin Wellington", song: "Iko Iko" },
  { artist: "Ini Kamoze", song: "Here Comes the Hotstepper" },
  { artist: "UB40", song: "Red Red Wine" },
  { artist: "Notch", song: "Nuttin Nuh Go So" },
  { artist: "Collie Buddz", song: "Love and Reggae" },
  { artist: "Musical Youth", song: "Pass The Dutchie" },
  { artist: "Toots and The Maytals", song: "Take Me Home, Country Roads" },
  { artist: "The Green", song: "Coming Home" },
  { artist: "Sister Nancy", song: "Bam Bam" },
  { artist: "Inner Circle", song: "Sweat" },
  { artist: "Rebelution", song: "Roots Reggae Music" },
  { artist: "Jimmy Cliff", song: "I Can See Clearly Now" },
  { artist: "Jimmy Cliff", song: "Many Rivers To Cross" },
  { artist: "Maoli Fiji and Jamey Ferguson", song: "Shoot Down" },
  { artist: "Johnny Cosmic", song: "Kingdom" },
  { artist: "The Elovaters", song: "Gimme Love" },
  { artist: "Jada Kingdom and Di Genius", song: "GPP" },
  { artist: "Matisyahu", song: "King Without a Crown" },
  { artist: "Safri Duo", song: "played a live" },
  { artist: "demarco", song: "i love my life" },
  { artist: "Tarrus Riley", song: "Shes Royal" },
  { artist: "Mad Cobra", song: "Flex" },
  { artist: "The Movement", song: "take me to the ocean" },
  { artist: "Jo Mersa Marley", song: "nothings gonna harm you" },
  { artist: "Jo Mersa Marley", song: "private beach party" },
  { artist: "Jo Mersa Marley", song: "guess whos comming home" },
  { artist: "gyptian", song: "hold you" },
  { artist: "pepper", song: "stone love" },
];

const RAP_SONGS = [
  { artist: "The Weeknd", song: "Creepin" },
  { artist: "Eminem", song: "Lose Yourself" },
  { artist: "Eminem", song: "without me" },
  { artist: "Eminem", song: "Mockingbird" },
  { artist: "Eminem", song: "not afraid" },
  { artist: "Eminem", song: "the real slim shady" },
  { artist: "Eminem", song: "the monster" },
  { artist: "Eminem", song: "stan" },
  { artist: "Post Malone", song: "I Like You" },
  { artist: "Post Malone", song: "sunflower" },
  { artist: "Post Malone", song: "rockstar" },
  { artist: "Post Malone", song: "circles" },
  { artist: "2pac", song: "california love" },
  { artist: "2pac", song: "dear mama" },
  { artist: "2pac", song: "Changes" },
  { artist: "2pac", song: "hit em up" },
  { artist: "Kanye West", song: "Stronger" },
  { artist: "Kanye West", song: "Runaway " },
  { artist: "Kanye West", song: "Flashing Lights" },
  { artist: "Kanye West", song: "gold digger" },
  { artist: "Salt-N-Pepa", song: "Push It" },
  { artist: "Salt-N-Pepa", song: "shoop" },
  { artist: "Salt-N-Pepa", song: "whatta man" },
  { artist: "timbaland", song: "give it to me" },
  { artist: "Timbaland", song: "The Way I Are" },
  { artist: "Kendrick Lamar", song: "HUMBLE" },
  { artist: "Kendrick Lamar", song: "All The Stars" },
  { artist: "50 Cent", song: "In da Club" },
  { artist: "Armani White", song: "BILLIE EILISH" },
  { artist: "cardy b", song: "wap" },
  { artist: "coolio", song: "gangstas paradise" },
  { artist: "Coi Leray", song: "Players" },
  { artist: "Connor Price", song: "spinnin" },
  { artist: "Dr. Dre", song: "the next episode" },
  { artist: "Drake", song: "Rich Flex" },
  { artist: "flo rida", song: "low" },
  { artist: "Future", song: "wait for you" },
  { artist: "House of Pain", song: "jump around" },
  { artist: "ice cube", song: "it was a good day" },
  { artist: "Jelly Roll", song: "Save Me" },
  { artist: "Jack Harlow", song: "First Class" },
  { artist: "JAY-Z", song: "Empire State Of Mind" },
  { artist: "Lil Durk", song: "Broadway Girls" },
  { artist: "Lil Uzi Vert", song: "Just Wanna Rock" },
  { artist: "Lil Jon", song: "get low" },
  { artist: "Lil Wayne", song: "lollipop" },
  { artist: "Lah Pat", song: "Rodeo" },
  { artist: "Moone Walker", song: "lizzo" },
  { artist: "Moni Meechi", song: "Like Whats up" },
  { artist: "Metro Boomin", song: "Superhero" },
  { artist: "montell jordan", song: "this is how we do it" },
  { artist: "Macklemore and Ryan Lewis", song: "cant hold us" },
  { artist: "Masked Wolf", song: "Astronaut In The Ocean" },
  { artist: "Nicki Minaj", song: "Super Freaky Girl" },
  { artist: "nelly", song: "Hot In Herre" },
  { artist: "GloRilla and Cardi B", song: "tomorrow 2" },
  { artist: "Yung Gravy", song: "betty" },
  { artist: "Wiz Khalifa", song: "see you again" },
  { artist: "vanilla ice", song: "ice ice baby" },
  { artist: "outkast", song: "hey ya" },
  { artist: "Tech N9ne", song: "Erbody But Me" },
  { artist: "Quavo and Takeoff", song: "HOTEL LOBBY" },
  { artist: "The Notorious B.I.G.", song: "Hypnotize" },
  { artist: "Outkast", song: "Ms. Jackson" },
  { artist: "Saweetie", song: "best friend" },
];

const POP_SONGS = [
  { artist: "Adele", song: "Set Fire to the Rain" },
  { artist: "Adele", song: "Someone Like You" },
  { artist: "Adele", song: "Hello" },
  { artist: "Andra Day", song: "Rise Up" },
  { artist: "abba", song: "the winner takes it all" },
  { artist: "britney spears", song: "toxic" },
  { artist: "britney spears", song: "oops i did it again" },
  { artist: "britney spears", song: "baby one more time" },
  { artist: "britney spears", song: "crazy" },
  { artist: "britney spears", song: "stronger" },
  { artist: "britney spears", song: "born to make you happy" },
  { artist: "Beyoncé", song: "Halo" },
  { artist: "beyonce", song: "cuff it" },
  { artist: "beyonce", song: "run the world" },
  { artist: "beyonce", song: "halo" },
  { artist: "Beyoncé", song: "Love on Top" },
  { artist: "beyonce", song: "single ladies" },
  { artist: "beyonce", song: "crazy in love" },
  { artist: "beyonce", song: "partition" },
  { artist: "Bruno Mars", song: "Uptown Funk" },
  { artist: "Bonny tyler", song: "total eclipse of the heart" },
  { artist: "Celine Dion", song: "My Heart Will Go On" },
  { artist: "Celine Dion", song: "its all coming back to me know" },
  { artist: "cyndi lauper", song: "girls just want to have fun" },
  { artist: "Ed Sheeran", song: "shape of you" },
  { artist: "Ed Sheeran", song: "castle on the hill" },
  { artist: "Ed Sheeran", song: "thinking out loud" },
  { artist: "Ed Sheeran", song: "perfect" },
  { artist: "Ed Sheeran", song: "the a team" },
  { artist: "Ed Sheeran", song: "Thinking Out Loud" },
  { artist: "eurythmix", song: "sweet dreams" },
  { artist: "Harry Styles", song: "as i was" },
  { artist: "lady gaga", song: "bad romance" },
  { artist: "lady gaga", song: "just dance" },
  { artist: "lady gaga", song: "poker face" },
  { artist: "lady gaga", song: "bloody mary" },
  { artist: "lady gaga", song: "alejandro" },
  { artist: "lady gaga", song: "telephone" },
  { artist: "lady gaga", song: "paparazzo" },
  { artist: "Lady Gaga and Bradley Cooper", song: "Shallow" },
  { artist: "lizzo", song: "about damn time" },
  { artist: "lizzo", song: "juice" },
  { artist: "lizzo", song: "good as hell" },
  { artist: "lizzo", song: "cuz i love you" },
  { artist: "Meghan Trainor", song: "all about that bass" },
  { artist: "Meghan Trainor", song: "made you look" },
  { artist: "nsync", song: "bye bye bye" },
  { artist: "nsync", song: "tearing up my heart" },
  { artist: "nsync", song: "its gonna be me" },
  { artist: "nsync", song: "pop" },
  { artist: "nsync", song: "girlfriend" },
  { artist: "sia", song: "Unstoppable" },
  { artist: "sia", song: "cheap thrills" },
  { artist: "sia", song: "chandelier" },
  { artist: "sia", song: "genius" },
  { artist: "sia", song: "alive" },
  { artist: "Tom MacDonald", song: "Ghost" },
  { artist: "Sam Smith", song: "Unholy" },
  { artist: "Rihanna", song: "Love on the Brain" },
  { artist: "Rihanna", song: "umbrella" },
  { artist: "Rihanna and Mikky Ekko", song: "Stay" },
  { artist: "Luis Fonsi and Daddy Yankee", song: "Despacito" },
  { artist: "Justin Bieber", song: "Sorry" },
  { artist: "Justin Bieber", song: "Baby" },
  { artist: "Wiz Khalifa and Charlie Puth", song: "See You Again" },
  { artist: "Justin Timberlake", song: "Can't Stop the Feeling!" },
  { artist: "Maroon 5", song: "Sugar" },
  { artist: "Taylor Swift", song: "Blank Space" },
  { artist: "Taylor Swift", song: "Anti Hero" },
  { artist: "Taylor Swift", song: "Shake It Off" },
  { artist: "Macklemore and Ryan Lewis", song: "Can't Hold Us" },
  { artist: "Pharrell Williams", song: "Happy" },
  { artist: "Katy Perry", song: "Roar" },
  { artist: "OneRepublic", song: "I Aint Worried" },
  { artist: "OneRepublic", song: "Counting Stars" },
  { artist: "John Legend", song: "All of Me" },
  { artist: "Whitney Houston", song: "I Will Always Love You" },
  { artist: "Idina Menzel", song: "Let It Go" },
  { artist: "Bruno Mars", song: "Count on Me" },
  { artist: "Backstreet Boys", song: "I Want It That Way" },
  { artist: "Ed Sheeran", song: "Happier" },
  { artist: "The Chainsmokers and Halsey", song: "Closer" },
  { artist: "Carly Rae Jepsen", song: "Call Me Maybe" },
  { artist: "Christina Perri", song: "A Thousand Years" },
  { artist: "fun. and Janelle Monáe", song: "We Are Young" },
  { artist: "James Blunt", song: "Goodbye My Lover" },
  { artist: "Eminem and Rihanna", song: "Love the Way You Lie" },
  { artist: "Jason Mraz", song: "I'm Yours" },
  { artist: "George Jones", song: "He Stopped Loving Her Today" },
  { artist: "Lou Bega", song: "Mambo No. 5" },
  { artist: "The Prodigy", song: "Breathe" },
  { artist: "The Chainsmokers and Coldplay", song: "Something Just Like This" },
  { artist: "Travie McCoy and Bruno Mars", song: "Billionaire" },
  { artist: "Mr. Probz", song: "Waves" },
  { artist: "Sam Smith", song: "I'm Not the Only One" },
  { artist: "The Weeknd", song: "Can't Feel My Face" },
];

const ROCK_SONGS = [
  { artist: "aerosmith", song: "hole in my soul" },
  { artist: "aerosmith", song: "Dream On" },
  { artist: "aerosmith", song: "amazing" },
  { artist: "aerosmith", song: "crazy" },
  { artist: "Aerosmith", song: "Cryin'" },
  { artist: "aerosmith", song: "pink" },
  { artist: "aerosmith", song: "walk this way" },
  { artist: "alice in chains", song: "rooster" },
  { artist: "alice in chains", song: "nutshell" },
  { artist: "alice in chains", song: "down in a hole" },
  { artist: "acdc", song: "Thunderstruck" },
  { artist: "acdc", song: "Highway To Hell" },
  { artist: "Alter Bridge", song: "Blackbird" },
  { artist: "Alter Bridge", song: "Metalingus" },
  { artist: "amy winehouse", song: "rehab" },
  { artist: "amy winehouse", song: "valerie" },
  { artist: "arctic monkeys", song: "i wanna be yours" },
  { artist: "arctic monkeys", song: "do i wanna know" },
  { artist: "arctic monkeys", song: "why'd you only call me when you're high" },
  { artist: "Arctic Monkeys", song: "Do Me a Favour" },
  { artist: "arctic monkeys", song: "r u mine" },
  { artist: "arctic monkeys", song: "505" },
  { artist: "Avenged Sevenfold", song: "Nightmare" },
  { artist: "Avenged Sevenfold", song: "A Little Piece of Heaven" },
  { artist: "beastie boys", song: "sabotage" },
  { artist: "beastie boys", song: "intergalactic" },
  { artist: "beastie boys", song: "no sleep till brooklyn" },
  { artist: "beastie boys", song: "fight for your right" },
  { artist: "Bryan Adams", song: "Summer of '69" },
  { artist: "the beatles", song: "hey jude" },
  { artist: "the beatles", song: "yesterday" },
  { artist: "the beatles", song: "i wanna hold your hand" },
  { artist: "the beatles", song: "yellow submarine" },
  { artist: "the beatles", song: "let it be" },
  { artist: "the beatles", song: "don't let me down" },
  { artist: "the beatles", song: "here comes the sun" },
  { artist: "the beatles", song: "come together" },
  { artist: "the beatles", song: "twist and shout" },
  { artist: "the beatles", song: "blackbird" },
  { artist: "the beatles", song: "help!" },
  { artist: "the beatles", song: "in my life" },
  { artist: "the beatles", song: "love me do" },
  { artist: "the beatles", song: "lucy in the sky with diamonds" },
  { artist: "Bon Jovi", song: "Wanted Dead or Alive" },
  { artist: "Bon Jovi", song: "always" },
  { artist: "Bon Jovi", song: "it's my life" },
  { artist: "Bon Jovi", song: "livin' on a prayer" },
  { artist: "Bon Jovi", song: "you give love a bad name" },
  { artist: "Bon Jovi", song: "bed of roses" },
  { artist: "Bon Jovi", song: "runaway" },
  { artist: "Bon Jovi", song: "keep the faith" },
  { artist: "Bon Jovi", song: "these days" },
  { artist: "The Black Keys", song: "Tighten Up" },
  { artist: "The Black Keys", song: "Lonely Boy" },
  { artist: "beck", song: "loser" },
  { artist: "beck", song: "where it's at" },
  { artist: "beck", song: "lost cause" },
  { artist: "billy idol", song: "white wedding" },
  { artist: "billy idol", song: "cradle of love" },
  { artist: "Black Sabbath", song: "Paranoid" },
  { artist: "Black Sabbath", song: "Iron Man" },
  { artist: "Blink-182", song: "All the Small Things" },
  { artist: "Blink-182", song: "What's My Age Again?" },
  { artist: "Blink-182", song: "adam's song" },
  { artist: "Coldplay", song: "Viva La Vida" },
  { artist: "Coldplay", song: "Fix You" },
  { artist: "The Calling", song: "Wherever You Will Go" },
  { artist: "The Cure", song: "Just Like Heaven" },
  { artist: "The Cure", song: "Friday I'm In Love" },
  { artist: "Creedence Clearwater Revival", song: "Proud Mary" },
  { artist: "Creedence Clearwater Revival", song: "i put a spell on you" },
  { artist: "Creedence Clearwater Revival", song: "Fortunate Son" },
  {
    artist: "Creedence Clearwater Revival",
    song: "have you ever seen the rain",
  },
  { artist: "Def Leppard", song: "Photograph" },
  { artist: "Deep Purple", song: "Child in Time" },
  { artist: "Deep Purple", song: "Smoke on the Water" },
  { artist: "Dio", song: "Rainbow in the Dark" },
  { artist: "Dio", song: "Holy Diver" },
  { artist: "The Doors", song: "Break On Through (To the Other Side)" },
  { artist: "The Doors", song: "Light My Fire" },
  { artist: "The Doors", song: "riders on the storm" },
  { artist: "The Doors", song: "people are strange" },
  { artist: "Def Leppard", song: "Pour Some Sugar On Me" },
  { artist: "The Eagles", song: "Hotel California" },
  { artist: "The Eagles", song: "Take It to the Limit" },
  { artist: "Evanescence", song: "Bring Me to Life" },
  { artist: "Evanescence", song: "My Immortal" },
  { artist: "Foo Fighters", song: "Everlong" },
  { artist: "Foo Fighters", song: "The Pretender" },
  { artist: "Foo Fighters", song: "My Hero" },
  { artist: "Foo Fighters", song: "times like these" },
  { artist: "Foo Fighters", song: "learn to fly" },
  { artist: "Foo Fighters", song: "Best of You" },
  { artist: "Foo Fighters", song: "all my life" },
  { artist: "Foo Fighters", song: "monkey wrench" },
  { artist: "Foo Fighters", song: "walking after you" },
  { artist: "Guns N' Roses", song: "Sweet Child o' Mine" },
  { artist: "Guns N' Roses", song: "Paradise City" },
  { artist: "Guns N' Roses", song: "november rain" },
  { artist: "Guns N' Roses", song: "welcome to the jungle" },
  { artist: "Guns N' Roses", song: "knockin' on heaven's door" },
  { artist: "Guns N' Roses", song: "live and let die" },
  { artist: "Green Day", song: "Boulevard of Broken Dreams" },
  { artist: "Green Day", song: "Good Riddance (Time of Your Life)" },
  { artist: "Green Day", song: "basket case" },
  { artist: "Green Day", song: "good ridance" },
  { artist: "Green Day", song: "when i come around" },
  { artist: "Green Day", song: "welcome to paradise" },
  { artist: "Green Day", song: "hitchin a ride" },
  { artist: "Green Day", song: "she" },
  { artist: "Green Day", song: "boulevard of broken dreams" },
  { artist: "The Hives", song: "Hate to Say I Told You So" },
  { artist: "The Hives", song: "Main Offender" },
  { artist: "Van Halen", song: "Jump" },
  { artist: "Van Halen", song: "Ain't Talkin' 'Bout Love" },
  { artist: "Iron Maiden", song: "Hallowed Be Thy Name" },
  { artist: "Iron Maiden", song: "Run to the Hills" },
  { artist: "Iron Maiden", song: "Fear of the Dark" },
  { artist: "Judas Priest", song: "Breaking the Law" },
  { artist: "Jimi Hendrix", song: "Purple Haze" },
  { artist: "Jimi Hendrix", song: "All Along the Watchtower" },
  { artist: "Judas Priest", song: "Painkiller" },
  { artist: "Journey", song: "Separate Ways (Worlds Apart)" },
  { artist: "Journey", song: "Don't Stop Believin'" },
  { artist: "Kings of Leon", song: "Sex on Fire" },
  { artist: "Kings of Leon", song: "Use Somebody" },
  { artist: "The Killers", song: "Mr. Brightside" },
  { artist: "The Killers", song: "When You Were Young" },
  { artist: "Kiss", song: "Love Gun" },
  { artist: "Kiss", song: "Rock and Roll All Nite" },
  { artist: "kate buse", song: "running up that hill" },
  { artist: "Linkin Park", song: "In the End" },
  { artist: "Linkin Park", song: "Crawling" },
  { artist: "Lamb of God", song: "Redneck" },
  { artist: "Lamb of God", song: "Laid to Rest" },
  { artist: "Led Zeppelin", song: "Stairway to Heaven" },
  { artist: "Led Zeppelin", song: "Kashmir" },
  { artist: "Motley Crue", song: "Dr. Feelgood" },
  { artist: "Motley Crue", song: "Girls, Girls, Girls" },
  { artist: "Muse", song: "Uprising" },
  { artist: "Muse", song: "Madness" },
  { artist: "Metallica", song: "Master of Puppets" },
  { artist: "Metallica", song: "Enter Sandman" },
  { artist: "Nirvana", song: "Come as You Are" },
  { artist: "Nirvana", song: "Smells Like Teen Spirit" },
  { artist: "The Offspring", song: "Self Esteem" },
  { artist: "The Offspring", song: "Come Out and Play (Keep 'Em Separated)" },
  { artist: "Oasis", song: "Wonderwall" },
  { artist: "Oasis", song: "Don't Look Back in Anger" },
  { artist: "Pearl Jam", song: "Alive" },
  { artist: "Pearl Jam", song: "Jeremy" },
  { artist: "Pink Floyd", song: "Another Brick in the Wall" },
  { artist: "Pink Floyd", song: "Shine On You Crazy Diamond" },
  { artist: "The Police", song: "Every Breath You Take" },
  { artist: "The Police", song: "Roxanne" },
  { artist: "Queen", song: "Bohemian Rhapsody" },
  { artist: "Queen", song: "We Will Rock You" },
  { artist: "The Rolling Stones", song: "Satisfaction" },
  { artist: "The Rolling Stones", song: "Gimme Shelter" },
  { artist: "Radiohead", song: "Paranoid Android" },
  { artist: "Radiohead", song: "Karma Police" },
  { artist: "Red Hot Chili Peppers", song: "Californication" },
  { artist: "Red Hot Chili Peppers", song: "Scar Tissue" },
  { artist: "Rage Against the Machine", song: "Killing in the Name" },
  { artist: "Slipknot", song: "Psychosocial" },
  { artist: "Slipknot", song: "Duality" },
  { artist: "System of a Down", song: "Chop Suey!" },
  { artist: "System of a Down", song: "Toxicity" },
  { artist: "Sum 41", song: "Fat Lip" },
  { artist: "Sum 41", song: "Still Waiting" },
  { artist: "The Strokes", song: "Last Nite" },
  { artist: "The Strokes", song: "Someday" },
  { artist: "The Verve", song: "Lucky Man" },
  { artist: "The Who", song: "Baba O'Riley" },
  { artist: "The Who", song: "Won't Get Fooled Again" },
  { artist: "Weezer", song: "Buddy Holly" },
  { artist: "Weezer", song: "Say It Ain't So" },
  { artist: "The White Stripes", song: "Seven Nation Army" },
  { artist: "The White Stripes", song: "Icky Thump" },
  { artist: "U2", song: "With or Without You" },
  { artist: "U2", song: "One" },
];

const ELECTRONIC_SONGS = [
  { artist: "Justice", song: "Genesis" },
  { artist: "Justice", song: "Phantom" },
  { artist: "Justice", song: "D.A.N.C.E." },
  { artist: "The Orb", song: "Perpetual Dawn" },
  { artist: "The Orb", song: "Blue Room" },
  { artist: "The Orb", song: "Little Fluffy Clouds" },
  { artist: "The Chemical Brothers", song: "Hey Boy Hey Girl" },
  { artist: "The Chemical Brothers", song: "Block Rockin' Beats" },
  { artist: "The Chemical Brothers", song: "Go" },
  { artist: "The Chemical Brothers", song: "Setting Sun" },
  { artist: "The Prodigy", song: "Firestarter" },
  { artist: "The Prodigy", song: "Breathe" },
  { artist: "The Prodigy", song: "Smack My Bitch Up" },
  { artist: "The Prodigy", song: "Voodoo People" },
  { artist: "The Crystal Method", song: "Name of the Game" },
  { artist: "The Crystal Method", song: "Busy Child" },
  { artist: "The Crystal Method", song: "Keep Hope Alive" },
  { artist: "The Crystal Method", song: "Trip Like I Do" },
  { artist: "Fatboy Slim", song: "The Rockafeller Skank" },
  { artist: "Fatboy Slim", song: "Praise You" },
  { artist: "Fatboy Slim", song: "Right Here, Right Now" },
  { artist: "Fatboy Slim", song: "Weapon of Choice" },
  { artist: "The Postal Service", song: "We Will Become Silhouettes" },
  { artist: "The Postal Service", song: "Such Great Heights" },
  { artist: "The Postal Service", song: "The District Sleeps Alone Tonight" },
  { artist: "deadmau5", song: "Strobe" },
  { artist: "deadmau5", song: "Ghosts 'n' Stuff" },
  { artist: "deadmau5", song: "Sofi Needs a Ladder" },
  { artist: "Moby", song: "Porcelain" },
  { artist: "Moby", song: "Natural Blues" },
  { artist: "Moby", song: "Why Does My Heart Feel So Bad?" },
  { artist: "Daft Punk", song: "Technologic" },
  { artist: "The Knife", song: "Heartbeats" },
  { artist: "The Knife", song: "Pass This On" },
  { artist: "The Knife", song: "Silent Shout" },
];

const BOYBANDS_SONGS = [
  { artist: "Backstreet Boys", song: "I Want It That Way" },
  { artist: "Backstreet Boys", song: "Everybody (Backstreet's Back)" },
  { artist: "Backstreet Boys", song: "Quit Playing Games (With My Heart)" },
  { artist: "Backstreet Boys", song: "As Long as You Love Me" },
  { artist: "Boyzone", song: "No Matter What" },
  { artist: "Boyzone", song: "Words" },
  { artist: "Boyzone", song: "Picture of You" },
  { artist: "BTS", song: "I Need U" },
  { artist: "BTS", song: "Boy With Luv" },
  { artist: "BTS", song: "Dynamite" },
  { artist: "NSYNC", song: "Tearin' Up My Heart" },
  { artist: "NSYNC", song: "It's Gonna Be Me" },
  { artist: "NSYNC", song: "Bye Bye Bye" },
  { artist: "New Kids on the Block", song: "You Got It (The Right Stuff)" },
  { artist: "New Kids on the Block", song: "Step by Step" },
  { artist: "New Kids on the Block", song: "Hangin' Tough" },
  { artist: "Westlife", song: "World of Our Own" },
  { artist: "Westlife", song: "Flying Without Wings" },
  { artist: "Westlife", song: "Uptown Girl" },
  { artist: "One Direction", song: "What Makes You Beautiful" },
  { artist: "One Direction", song: "Story of My Life" },
  { artist: "One Direction", song: "Best Song Ever" },
  { artist: "The Wanted", song: "Glad You Came" },
  { artist: "The Wanted", song: "Chasing the Sun" },
  { artist: "The Wanted", song: "All Time Low" },
  { artist: "5 Seconds of Summer", song: "Amnesia" },
  { artist: "5 Seconds of Summer", song: "She Looks So Perfect" },
  { artist: "5 Seconds of Summer", song: "Good Girls" },
];

const MOVIES_SONGS = [
  { artist: "Celine Dion", song: "My Heart Will Go On" },
  { artist: "Whitney Houston", song: "I Will Always Love You" },
  { artist: "Madonna", song: "Into the Groove" },
  { artist: "Mark Knopfler", song: "The Princess Bride (Storybook Love)" },
  { artist: "Elton John", song: "Can You Feel the Love Tonight" },
  { artist: "John Williams", song: "Star Wars Main Theme" },
  { artist: "Pharrell Williams", song: "Happy" },
  { artist: "Bruno Mars", song: "Uptown Funk" },
  { artist: "Lorde", song: "Yellow Flicker Beat" },
  { artist: "M83", song: "Midnight City" },
  { artist: "The Lumineers", song: "Ho Hey" },
  { artist: "The Weeknd", song: "Earned It" },
  { artist: "Frozen", song: "Let It Go" },
  { artist: "Diana Ross", song: "I'm Coming Out" },
  { artist: "Cher", song: "Believe" },
  { artist: "Bee Gees", song: "Stayin' Alive" },
  { artist: "Earth, Wind & Fire", song: "September" },
  { artist: "The Pointer Sisters", song: "I'm So Excited" },
  { artist: "ABBA", song: "Dancing Queen" },
  { artist: "ABBA", song: "Mamma Mia" },
  { artist: "Bee Gees", song: "Night Fever" },
  { artist: "Earth, Wind & Fire", song: "Let's Groove" },
  { artist: "Michael Jackson", song: "Billie Jean" },
  { artist: "The Pointer Sisters", song: "Neutron Dance" },
  { artist: "ABBA", song: "Take a Chance on Me" },
  { artist: "Bee Gees", song: "You Should Be Dancing" },
  { artist: "Michael Jackson", song: "Don't Stop 'Til You Get Enough" },
  { artist: "Bee Gees", song: "How Deep Is Your Love" },
  { artist: "Earth, Wind & Fire", song: "Boogie Wonderland" },
  { artist: "Michael Jackson", song: "Rock with You" },
];

const LATIN_SONGS = [
  { artist: "Shakira", song: "Waka Waka (This Time for Africa)" },
  { artist: "Shakira", song: "Whenever, Wherever" },
  { artist: "Shakira", song: "Hips Don't Lie" },
  { artist: "Ricky Martin", song: "Livin' la Vida Loca" },
  { artist: "Ricky Martin", song: "She Bangs" },
  { artist: "Enrique Iglesias", song: "Bailamos" },
  { artist: "Enrique Iglesias", song: "Hero" },
  { artist: "Marc Anthony", song: "You Sang to Me" },
  { artist: "Marc Anthony", song: "I Need to Know" },
  { artist: "Santana", song: "Smooth" },
  { artist: "Santana", song: "Maria Maria" },
  { artist: "Santana", song: "Black Magic Woman" },
  { artist: "Jenifer Lopez", song: "Love Don't Cost a Thing" },
  { artist: "J. Lo", song: "Get Right" },
  { artist: "J Balvin", song: "Mi Gente" },
  { artist: "J Balvin", song: "Ginza" },
  { artist: "J Balvin", song: "Ay Vamos" },
  { artist: "Luis Fonsi", song: "Despacito" },
  { artist: "Luis Fonsi", song: "Echame La Culpa" },
  { artist: "Bad Bunny", song: "Soy Peor" },
  { artist: "Juanes", song: "A Dios Le Pido" },
  { artist: "Gloria Estefan", song: "Rhythm Is Gonna Get You" },
  { artist: "Gloria Estefan", song: "Don't Wanna Lose You" },
  { artist: "Alejandro Sanz", song: "La Tortura" },
  { artist: "Alejandro Sanz", song: "Corazon Partio" },
  { artist: "Daddy Yankee", song: "Dura" },
  { artist: "Daddy Yankee", song: "Lo Que Pasó, Pasó" },
  { artist: "Daddy Yankee", song: "Gasolina" },
  { artist: "Romeo Santos", song: "Propuesta Indecente" },
  { artist: "Romeo Santos", song: "Eres Mía" },
  { artist: "Ozuna", song: "Te Vas" },
  { artist: "Ozuna", song: "El Farsante" },
  { artist: "Ozuna", song: "Dile Que Tu Me Quieres" },
  { artist: "Luis Fonsi", song: "Imposible" },
  { artist: "Bad Bunny", song: "Estamos Bien" },
  { artist: "Bad Bunny", song: "Mia" },
  { artist: "Nicky Jam", song: "El Amante" },
  { artist: "Nicky Jam", song: "El Favor" },
  { artist: "Nicky Jam", song: "El Perdón" },
  { artist: "Juanes", song: "La Camisa Negra" },
  { artist: "Maluma", song: "Felices los 4" },
  { artist: "Maluma", song: "Sin Contrato" },
  { artist: "Enrique Iglesias", song: "Escape" },
  { artist: "Carlos Vives", song: "La Gota Fria" },
  { artist: "Carlos Vives", song: "Fruta Fresca" },
];

export const categories = {
  rock: ROCK_SONGS,
  electronic: ELECTRONIC_SONGS,
  pop: POP_SONGS,
  reggae: REGGAE_SONGS,
  rap: RAP_SONGS,
  movies: MOVIES_SONGS,
  boyBands: BOYBANDS_SONGS,
  latin: LATIN_SONGS,
};

// for (const category in categories) {
//   const arrOfSongs = categories[category];
//   const duplicates = [];
//   const songTitles = [];
//   arrOfSongs.forEach(async (song) => {
//     const { artist, song: title } = song;
//     if (songTitles.includes(title)) {
//       duplicates.push(song);
//     } else {
//       songTitles.push(title);
//     }
//   });
//   console.log(duplicates);
// }
